/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';
import '@stencil/state-tunnel';
import '@ionic/core';
import 'ionicons';

import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface AppApplyCard {
      'history': RouterHistory;
    }
  }

  interface HTMLAppApplyCardElement extends StencilComponents.AppApplyCard, HTMLStencilElement {}

  var HTMLAppApplyCardElement: {
    prototype: HTMLAppApplyCardElement;
    new (): HTMLAppApplyCardElement;
  };
  interface HTMLElementTagNameMap {
    'app-apply-card': HTMLAppApplyCardElement;
  }
  interface ElementTagNameMap {
    'app-apply-card': HTMLAppApplyCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-apply-card': JSXElements.AppApplyCardAttributes;
    }
  }
  namespace JSXElements {
    export interface AppApplyCardAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppApplyAudit {
      'history': RouterHistory;
    }
  }

  interface HTMLAppApplyAuditElement extends StencilComponents.AppApplyAudit, HTMLStencilElement {}

  var HTMLAppApplyAuditElement: {
    prototype: HTMLAppApplyAuditElement;
    new (): HTMLAppApplyAuditElement;
  };
  interface HTMLElementTagNameMap {
    'app-apply-audit': HTMLAppApplyAuditElement;
  }
  interface ElementTagNameMap {
    'app-apply-audit': HTMLAppApplyAuditElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-apply-audit': JSXElements.AppApplyAuditAttributes;
    }
  }
  namespace JSXElements {
    export interface AppApplyAuditAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppApplyBack {
      'history': RouterHistory;
    }
  }

  interface HTMLAppApplyBackElement extends StencilComponents.AppApplyBack, HTMLStencilElement {}

  var HTMLAppApplyBackElement: {
    prototype: HTMLAppApplyBackElement;
    new (): HTMLAppApplyBackElement;
  };
  interface HTMLElementTagNameMap {
    'app-apply-back': HTMLAppApplyBackElement;
  }
  interface ElementTagNameMap {
    'app-apply-back': HTMLAppApplyBackElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-apply-back': JSXElements.AppApplyBackAttributes;
    }
  }
  namespace JSXElements {
    export interface AppApplyBackAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppApplyLaunch {
      'history': RouterHistory;
    }
  }

  interface HTMLAppApplyLaunchElement extends StencilComponents.AppApplyLaunch, HTMLStencilElement {}

  var HTMLAppApplyLaunchElement: {
    prototype: HTMLAppApplyLaunchElement;
    new (): HTMLAppApplyLaunchElement;
  };
  interface HTMLElementTagNameMap {
    'app-apply-launch': HTMLAppApplyLaunchElement;
  }
  interface ElementTagNameMap {
    'app-apply-launch': HTMLAppApplyLaunchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-apply-launch': JSXElements.AppApplyLaunchAttributes;
    }
  }
  namespace JSXElements {
    export interface AppApplyLaunchAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppScholarshipAudit {
      'history': RouterHistory;
    }
  }

  interface HTMLAppScholarshipAuditElement extends StencilComponents.AppScholarshipAudit, HTMLStencilElement {}

  var HTMLAppScholarshipAuditElement: {
    prototype: HTMLAppScholarshipAuditElement;
    new (): HTMLAppScholarshipAuditElement;
  };
  interface HTMLElementTagNameMap {
    'app-scholarship-audit': HTMLAppScholarshipAuditElement;
  }
  interface ElementTagNameMap {
    'app-scholarship-audit': HTMLAppScholarshipAuditElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-scholarship-audit': JSXElements.AppScholarshipAuditAttributes;
    }
  }
  namespace JSXElements {
    export interface AppScholarshipAuditAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppScholarshipBack {
      'history': RouterHistory;
    }
  }

  interface HTMLAppScholarshipBackElement extends StencilComponents.AppScholarshipBack, HTMLStencilElement {}

  var HTMLAppScholarshipBackElement: {
    prototype: HTMLAppScholarshipBackElement;
    new (): HTMLAppScholarshipBackElement;
  };
  interface HTMLElementTagNameMap {
    'app-scholarship-back': HTMLAppScholarshipBackElement;
  }
  interface ElementTagNameMap {
    'app-scholarship-back': HTMLAppScholarshipBackElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-scholarship-back': JSXElements.AppScholarshipBackAttributes;
    }
  }
  namespace JSXElements {
    export interface AppScholarshipBackAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppScholarshipLaunch {
      'history': RouterHistory;
    }
  }

  interface HTMLAppScholarshipLaunchElement extends StencilComponents.AppScholarshipLaunch, HTMLStencilElement {}

  var HTMLAppScholarshipLaunchElement: {
    prototype: HTMLAppScholarshipLaunchElement;
    new (): HTMLAppScholarshipLaunchElement;
  };
  interface HTMLElementTagNameMap {
    'app-scholarship-launch': HTMLAppScholarshipLaunchElement;
  }
  interface ElementTagNameMap {
    'app-scholarship-launch': HTMLAppScholarshipLaunchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-scholarship-launch': JSXElements.AppScholarshipLaunchAttributes;
    }
  }
  namespace JSXElements {
    export interface AppScholarshipLaunchAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppDoneList {
      'flowCode': string;
      'history': RouterHistory;
    }
  }

  interface HTMLAppDoneListElement extends StencilComponents.AppDoneList, HTMLStencilElement {}

  var HTMLAppDoneListElement: {
    prototype: HTMLAppDoneListElement;
    new (): HTMLAppDoneListElement;
  };
  interface HTMLElementTagNameMap {
    'app-done-list': HTMLAppDoneListElement;
  }
  interface ElementTagNameMap {
    'app-done-list': HTMLAppDoneListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-done-list': JSXElements.AppDoneListAttributes;
    }
  }
  namespace JSXElements {
    export interface AppDoneListAttributes extends HTMLAttributes {
      'flowCode'?: string;
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppFlowList {
      'history': RouterHistory;
      'match': MatchResults;
    }
  }

  interface HTMLAppFlowListElement extends StencilComponents.AppFlowList, HTMLStencilElement {}

  var HTMLAppFlowListElement: {
    prototype: HTMLAppFlowListElement;
    new (): HTMLAppFlowListElement;
  };
  interface HTMLElementTagNameMap {
    'app-flow-list': HTMLAppFlowListElement;
  }
  interface ElementTagNameMap {
    'app-flow-list': HTMLAppFlowListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-flow-list': JSXElements.AppFlowListAttributes;
    }
  }
  namespace JSXElements {
    export interface AppFlowListAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHistoryList {
      'history': RouterHistory;
    }
  }

  interface HTMLAppHistoryListElement extends StencilComponents.AppHistoryList, HTMLStencilElement {}

  var HTMLAppHistoryListElement: {
    prototype: HTMLAppHistoryListElement;
    new (): HTMLAppHistoryListElement;
  };
  interface HTMLElementTagNameMap {
    'app-history-list': HTMLAppHistoryListElement;
  }
  interface ElementTagNameMap {
    'app-history-list': HTMLAppHistoryListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-history-list': JSXElements.AppHistoryListAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHistoryListAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHome {
      'history': RouterHistory;
      'match': MatchResults;
    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppMain {

    }
  }

  interface HTMLAppMainElement extends StencilComponents.AppMain, HTMLStencilElement {}

  var HTMLAppMainElement: {
    prototype: HTMLAppMainElement;
    new (): HTMLAppMainElement;
  };
  interface HTMLElementTagNameMap {
    'app-main': HTMLAppMainElement;
  }
  interface ElementTagNameMap {
    'app-main': HTMLAppMainElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-main': JSXElements.AppMainAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMainAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppTodoList {
      'callback': Function;
      'flowCode': string;
      'history': RouterHistory;
    }
  }

  interface HTMLAppTodoListElement extends StencilComponents.AppTodoList, HTMLStencilElement {}

  var HTMLAppTodoListElement: {
    prototype: HTMLAppTodoListElement;
    new (): HTMLAppTodoListElement;
  };
  interface HTMLElementTagNameMap {
    'app-todo-list': HTMLAppTodoListElement;
  }
  interface ElementTagNameMap {
    'app-todo-list': HTMLAppTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-todo-list': JSXElements.AppTodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface AppTodoListAttributes extends HTMLAttributes {
      'callback'?: Function;
      'flowCode'?: string;
      'history'?: RouterHistory;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
